# prometheus-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: iot-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      # - "first.rules"
      # - "second.rules"
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # Scrape configuration for our iot-service
      - job_name: 'iot-service'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - iot-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_prometheus]
            regex: "true"
            action: keep
          - source_labels: [__meta_kubernetes_service_port_name]
            regex: "metrics"
            action: keep