apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: iot-system
  name: service-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
