apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "iot-system.name" . }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.timescaledb.database.name | b64enc }}
  POSTGRES_USER: {{ .Values.timescaledb.database.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.timescaledb.database.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "iot-system.name" . }}
type: Opaque
data:
  API_KEY: {{ .Values.apiCredentials.apiKey | b64enc }}
