apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-app-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- if .Values.ingress.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    {{- end }}
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: web-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-frontend
            port:
              number: 3000
  {{- if .Values.ingress.useTLS }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: iot-tls-cert
  {{- end }}