apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: iot-ca-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: iot-ca
