apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: {{ .Release.Namespace }}
  labels:
    app: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ include "iot-system.name" . }}
    app.kubernetes.io/version: "1.0.0"
    helm.sh/chart: {{ include "iot-system.chart" . }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- if .Values.mosquitto.service.annotations }}
    {{- toYaml .Values.mosquitto.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.mosquitto.service.type | default "ClusterIP" }}
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: mqtt
    - name: mqtts
      port: 8883
      protocol: TCP
      targetPort: mqtts
  selector:
    app: mosquitto
  sessionAffinity: None