apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: {{ .Release.Namespace }}
  labels:
    app: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "iot-system.name" . }}
    helm.sh/chart: {{ include "iot-system.chart" . }}
spec:
  replicas: {{ .Values.mosquitto.replicas }}
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mosquitto
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "iot-system.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: mosquitto
        image: "{{ .Values.mosquitto.image.repository }}:{{ .Values.mosquitto.image.tag }}"
        imagePullPolicy: {{ .Values.mosquitto.image.pullPolicy }}
        env:
        {{- range $index, $var := .Values.mosquitto.env }}
          - name: {{ $var.name }}
            value: "{{ $var.value }}"
        {{- end }}
        ports:
          - containerPort: 1883
            name: mqtt
            protocol: TCP
          - containerPort: 8883
            name: mqtts
            protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.mosquitto.resources.requests.cpu | quote }}
            memory: {{ .Values.mosquitto.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.mosquitto.resources.limits.cpu | quote }}
            memory: {{ .Values.mosquitto.resources.limits.memory | quote }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-log
          mountPath: /mosquitto/log
        - name: mosquitto-certs
          mountPath: /mosquitto/certs
          readOnly: true
        - name: mosquitto-passwd
          mountPath: /mosquitto/passwd
          readOnly: true
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
          defaultMode: 420
      - name: mosquitto-data
        emptyDir: {}
      - name: mosquitto-log
        emptyDir: {}
      - name: mosquitto-certs
        secret:
          secretName: mosquitto-certs
          defaultMode: 420
      - name: mosquitto-passwd
        secret:
          secretName: mosquitto-credentials
          defaultMode: 420
