{{- if .Values.certificates.mosquitto.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificates.mosquitto.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iot-system.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Files.Get "certs/ca.crt" | b64enc }}
  server.crt: {{ .Files.Get "certs/server.crt" | b64enc }}
  server.key: {{ .Files.Get "certs/server.key" | b64enc }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iot-system.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.timescaledb.database.name | b64enc }}
  POSTGRES_USER: {{ .Values.timescaledb.database.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.timescaledb.database.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iot-system.labels" . | nindent 4 }}
type: Opaque
data:
  IOT_SERVICE_USERNAME: {{ .Values.mosquitto.credentials.iotService.username | b64enc }}
  IOT_SERVICE_PASSWORD: {{ .Values.mosquitto.credentials.iotService.password | b64enc }}
  TEST_PUB_USERNAME: {{ .Values.mosquitto.credentials.testPub.username | b64enc }}
  TEST_PUB_PASSWORD: {{ .Values.mosquitto.credentials.testPub.password | b64enc }}
