apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: {{ .Release.Namespace }}
  labels:
    app: timescaledb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "iot-system.name" . }}
spec:
  replicas: {{ .Values.timescaledb.replicas | default 1 }}
  selector:
    matchLabels:
      app: timescaledb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: timescaledb
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "iot-system.name" . }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: timescaledb
        image: "{{ .Values.timescaledb.image.repository }}:{{ .Values.timescaledb.image.tag }}"
        imagePullPolicy: {{ .Values.timescaledb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.timescaledb.port }}
          name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            cpu: {{ .Values.timescaledb.resources.requests.cpu | quote }}
            memory: {{ .Values.timescaledb.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.timescaledb.resources.limits.cpu | quote }}
            memory: {{ .Values.timescaledb.resources.limits.memory | quote }}
        securityContext:
          runAsUser: {{ .Values.timescaledb.securityContext.runAsUser }}
          runAsNonRoot: {{ .Values.timescaledb.securityContext.runAsNonRoot }}
        volumeMounts:
        - name: timescaledb-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: timescaledb-data
        emptyDir: {}  # Persistence is disabled per values.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: {{ .Release.Namespace }}
  labels:
    app: timescaledb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "iot-system.name" . }}
spec:
  ports:
  - port: {{ .Values.timescaledb.port }}
    targetPort: {{ .Values.timescaledb.port }}
    protocol: TCP
    name: postgres
  selector:
    app: timescaledb