apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iot-system.labels" . | nindent 4 }}
    app: web-backend
spec:
  replicas: {{ .Values.webBackend.replicas }}
  selector:
    matchLabels:
      app: web-backend
  template:
    metadata:
      labels:
        app: web-backend
        {{- include "iot-system.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.webBackend.securityContext.runAsUser }}
        fsGroup: 2000
      containers:
      - name: web-backend
        image: "{{ .Values.webBackend.image.repository }}:{{ .Values.webBackend.image.tag }}"
        imagePullPolicy: {{ .Values.webBackend.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: {{ .Values.webBackend.securityContext.runAsUser }}
        ports:
        - containerPort: {{ .Values.webBackend.port }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: timescaledb
        - name: POSTGRES_PORT
          value: "{{ .Values.timescaledb.port }}"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-credentials
              key: API_KEY
        resources:
          {{- toYaml .Values.webBackend.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iot-system.labels" . | nindent 4 }}
    app: web-backend
spec:
  selector:
    app: web-backend
  ports:
    - protocol: TCP
      port: {{ .Values.webBackend.port }}
      targetPort: {{ .Values.webBackend.port }}
  type: {{ .Values.webBackend.service.type }}