name: Build and Push IoT Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set version tag
      id: vars
      run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Build and push iot-service
      uses: docker/build-push-action@v4
      with:
        context: ./iot_service
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/iot-service:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/iot-service:${{ steps.vars.outputs.SHA_SHORT }}
    
    - name: Build and push test-pub
      uses: docker/build-push-action@v4
      with:
        context: ./test_pub
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/test-pub:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/test-pub:${{ steps.vars.outputs.SHA_SHORT }}
    
    - name: Build and push web-frontend
      uses: docker/build-push-action@v4
      with:
        context: ./web/frontend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/web-frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/web-frontend:${{ steps.vars.outputs.SHA_SHORT }}
    
    - name: Build and push web-backend
      uses: docker/build-push-action@v4
      with:
        context: ./web/backend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/web-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/web-backend:${{ steps.vars.outputs.SHA_SHORT }}
